name: axolotl-pipeline
on: 
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  setting-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10'
          cache: 'npm' 
      - run: npm ci

  lint:
    needs: 'setting-up'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10'
          cache: 'npm'
      - run: npm ci
      - run: npm lint
  
  test:
    needs: 'setting-up'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10'
          cache: 'npm'
      - run: npm ci
      - run: npm test

        


      
